### ISSUE TITLE
Style_profile_xhtml.sas error

### ISSUE THREAD

**Issue by ptatian** [NeighborhoodInfoDC/Profiles#1]
*/ comment end placed too late when adding new page footer code. Should be before the prepost trigger statement. 

https://github.com/NeighborhoodInfoDC/Profiles/blob/master/Macros/Style_profile_xhtml.sas

**Comment by ptatian** [comment]
Issue I mentioned earlier. Would be good to fix this during the next update. Let me know if you have questions. 

Since you are working another issue for the profile update, I would suggest adding this task to that issue. Then, close this issue with a comment saying that the work will be done under issue #X.  I think this is cleaner than creating a multiple branches.

**Comment by rpitingolo** [comment]
Thanks. I was going to fix this bug for the update. I should have assigned it to myself.

**Comment by rpitingolo** [comment]
Made this edit as part of issue #6
