### ISSUE TITLE
Profile update

### ISSUE THREAD

**Issue by rpitingolo** [NeighborhoodInfoDC/Profiles#6]
Update for new ACS, Police, Realprop data.

**Comment by rpitingolo** [comment]
@ptatian we now have ACS data for non-overlapping years. For  the purpose of the profiles, I thought it made sense to order it: 2006-10 ACS, then 2010 Census, then 2011-15 ACS. Sound OK?

**Comment by ptatian** [comment]
Good idea to think of that. Actually, you wouldn't have 2010 census with the ACS numbers. I believe those sets of variables are mutually exclusive in our profiles. 

Only issue is whether we think its __reliable to compare the earlier and later ACS estimates__ in most cases. I don't want to put something out that will allow/encourage people to do things that don't make sense. Can you look at some of the bigger indicators (poverty, avg family income) and see if there are meaningful differences? 

@lhendey Any thoughts?

**Comment by rpitingolo** [comment]
What level of geography would be appropriate to do  that test? If they're meaningful at the ward but not the tract, would that be good enough. for example?

**Comment by ptatian** [comment]
I would look at city and ward.

**Comment by ptatian** [comment]
Rob, what is the status of the profile updates? We have a DC newsletter planned to go out April 5. Will we have the profiles updated by then? Thanks.

**Comment by rpitingolo** [comment]
Peter, I'm trying to sort out an issue with the NCDB files. It seems like re-running them caused some kind of change that it's now returning errors for the profiles. I'm trying to get this resolved as quickly as possible so we can get the profiles up this week.

**Comment by rpitingolo** [comment]
The profiles program is looking for the Pop65andOverYears variable on the NCDB files and that variable doesn't exist. It looks like I can add it into the program and re-run the summary files. I'll open a bug-fix issue on the NCDB repository.

**Comment by rpitingolo** [comment]
The profiles have been updated and uploaded, including the comparison tables. Please let me know if you see any issues. 

Once we receive and process the TANF/SNAP data we can re-run the profiles as well as update the source/notes to reflect what we know about the TANF data now. 

@NeighborhoodInfoDC/review
